# Generated by Django 5.1.1 on 2024-09-19 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('size_range', models.IntegerField()),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.CharField(max_length=100)),
                ('curr_emp_estimate', models.IntegerField()),
                ('total_emp_estimate', models.IntegerField()),
            ],
        ),
    ]
