# Generated by Django 5.1.1 on 2024-09-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydata',
            name='curr_emp_estimate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydata',
            name='linkedin_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydata',
            name='locality',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydata',
            name='size_range',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='companydata',
            name='total_emp_estimate',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
