# Generated by Django 5.1.1 on 2024-09-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_companydata_country_companydata_curr_emp_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='curr_emp_estimate',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='founded_year',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='size_range',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_emp_estimate',
            field=models.CharField(max_length=20),
        ),
    ]
