# Generated by Django 5.1.1 on 2024-09-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_companydata_curr_emp_estimate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='curr_emp_estimate',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='domain',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='founded_year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='linkedin_url',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='locality',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='size_range',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='total_emp_estimate',
            field=models.CharField(default='', max_length=20),
        ),
    ]
